name: Extract Domains from Discourse

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 */3 * *"
  workflow_dispatch:

jobs:
  extract-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r scripts/extract/requirements.txt

      - name: Fetch and extract code blocks
        run: python scripts/extract/main.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "chore: update extracted code blocks"
            git push
          else
            echo "No changes to commit"
          fi
